/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'voterId' : IDL.Opt(IDL.Text),
});
export const Candidate = IDL.Record({
  'id' : IDL.Nat,
  'voteCount' : IDL.Nat,
  'name' : IDL.Text,
  'partyName' : IDL.Text,
  'position' : IDL.Text,
});
export const ElectionStatus = IDL.Record({
  'totalVotes' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const CandidateDTO = IDL.Record({
  'id' : IDL.Nat,
  'voteCount' : IDL.Nat,
  'name' : IDL.Text,
  'votePercentage' : IDL.Float64,
  'partyName' : IDL.Text,
  'position' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCandidate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addVoter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'castVote' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
  'deleteCandidate' : IDL.Func([IDL.Nat], [], []),
  'deleteVoter' : IDL.Func([IDL.Text], [], []),
  'editCandidate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'endElection' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
  'getElectionStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getElectionSummary' : IDL.Func([], [ElectionStatus], ['query']),
  'getResults' : IDL.Func([], [IDL.Vec(CandidateDTO)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startElection' : IDL.Func([], [], []),
  'updateVoter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'voterId' : IDL.Opt(IDL.Text),
  });
  const Candidate = IDL.Record({
    'id' : IDL.Nat,
    'voteCount' : IDL.Nat,
    'name' : IDL.Text,
    'partyName' : IDL.Text,
    'position' : IDL.Text,
  });
  const ElectionStatus = IDL.Record({
    'totalVotes' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const CandidateDTO = IDL.Record({
    'id' : IDL.Nat,
    'voteCount' : IDL.Nat,
    'name' : IDL.Text,
    'votePercentage' : IDL.Float64,
    'partyName' : IDL.Text,
    'position' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCandidate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addVoter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'castVote' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
    'deleteCandidate' : IDL.Func([IDL.Nat], [], []),
    'deleteVoter' : IDL.Func([IDL.Text], [], []),
    'editCandidate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'endElection' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
    'getElectionStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getElectionSummary' : IDL.Func([], [ElectionStatus], ['query']),
    'getResults' : IDL.Func([], [IDL.Vec(CandidateDTO)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startElection' : IDL.Func([], [], []),
    'updateVoter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };