/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'id' : bigint,
  'voteCount' : bigint,
  'name' : string,
  'partyName' : string,
  'position' : string,
}
export interface CandidateDTO {
  'id' : bigint,
  'voteCount' : bigint,
  'name' : string,
  'votePercentage' : number,
  'partyName' : string,
  'position' : string,
}
export interface ElectionStatus { 'totalVotes' : bigint, 'isActive' : boolean }
export interface UserProfile { 'name' : string, 'voterId' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCandidate' : ActorMethod<[bigint, string, string, string], undefined>,
  'addVoter' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'castVote' : ActorMethod<[string, bigint, string], boolean>,
  'deleteCandidate' : ActorMethod<[bigint], undefined>,
  'deleteVoter' : ActorMethod<[string], undefined>,
  'editCandidate' : ActorMethod<[bigint, string, string, string], undefined>,
  'endElection' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidates' : ActorMethod<[], Array<Candidate>>,
  'getElectionStatus' : ActorMethod<[], boolean>,
  'getElectionSummary' : ActorMethod<[], ElectionStatus>,
  'getResults' : ActorMethod<[], Array<CandidateDTO>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startElection' : ActorMethod<[], undefined>,
  'updateVoter' : ActorMethod<[string, string, string], undefined>,
  'verifyOTP' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];